<?php

namespace ContainerPaupVtG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GepxwuRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gepxwuR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gepxwuR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'supplements' => ['privates', '.errored..service_locator.gepxwuR.App\\Entity\\Supplements', NULL, 'Cannot autowire service ".service_locator.gepxwuR": it references class "App\\Entity\\Supplements" but no such service exists.'],
        ], [
            'supplements' => 'App\\Entity\\Supplements',
        ]);
    }
}
