<?php

namespace ContainerPaupVtG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FCnhh3sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fCnhh3s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fCnhh3s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pannier' => ['privates', '.errored..service_locator.fCnhh3s.App\\Entity\\Pannier', NULL, 'Cannot autowire service ".service_locator.fCnhh3s": it references class "App\\Entity\\Pannier" but no such service exists.'],
        ], [
            'pannier' => 'App\\Entity\\Pannier',
        ]);
    }
}
