<?php

namespace ContainerPaupVtG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInfoBoutiqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Vv4yqUS.App\Entity\InfoBoutique' shared service.
     *
     * @return \App\Entity\InfoBoutique
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Vv4yqUS": it references class "App\\Entity\\InfoBoutique" but no such service exists.');
    }
}
