<?php

namespace ContainerPaupVtG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPannierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fCnhh3s.App\Entity\Pannier' shared service.
     *
     * @return \App\Entity\Pannier
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.fCnhh3s": it references class "App\\Entity\\Pannier" but no such service exists.');
    }
}
