<?php

namespace ContainerPaupVtG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSupplementsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gepxwuR.App\Entity\Supplements' shared service.
     *
     * @return \App\Entity\Supplements
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.gepxwuR": it references class "App\\Entity\\Supplements" but no such service exists.');
    }
}
