name: Deploy to GitHub Pages
on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-php@v2
        with:
          php-version: 8.0
      - run: composer install
      - run: symfony server:start
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        with:
          branch: production
          dotfiles: false
          publish_dir: public

