<?php

namespace ContainerJyFT97M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QyorV7dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qyorV7d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qyorV7d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'vacanceFermeture' => ['privates', '.errored..service_locator.qyorV7d.App\\Entity\\VacanceFermeture', NULL, 'Cannot autowire service ".service_locator.qyorV7d": it references class "App\\Entity\\VacanceFermeture" but no such service exists.'],
        ], [
            'vacanceFermeture' => 'App\\Entity\\VacanceFermeture',
        ]);
    }
}
