<?php

namespace ContainerJyFT97M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4fBkBblService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4fBkBbl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4fBkBbl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorie' => ['privates', '.errored..service_locator.4fBkBbl.App\\Entity\\Categories', NULL, 'Cannot autowire service ".service_locator.4fBkBbl": it references class "App\\Entity\\Categories" but no such service exists.'],
        ], [
            'categorie' => 'App\\Entity\\Categories',
        ]);
    }
}
