<?php

namespace ContainerJyFT97M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vv4yqUSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vv4yqUS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vv4yqUS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'infoBoutique' => ['privates', '.errored..service_locator.Vv4yqUS.App\\Entity\\InfoBoutique', NULL, 'Cannot autowire service ".service_locator.Vv4yqUS": it references class "App\\Entity\\InfoBoutique" but no such service exists.'],
        ], [
            'infoBoutique' => 'App\\Entity\\InfoBoutique',
        ]);
    }
}
