<?php

namespace ContainerJyFT97M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1ZfDXOMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1ZfDXOM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1ZfDXOM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'produits' => ['privates', '.errored..service_locator.1ZfDXOM.App\\Entity\\Produits', NULL, 'Cannot autowire service ".service_locator.1ZfDXOM": it references class "App\\Entity\\Produits" but no such service exists.'],
        ], [
            'produits' => 'App\\Entity\\Produits',
        ]);
    }
}
