<?php

namespace ContainerJyFT97M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IzzSjsoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IzzSjso' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IzzSjso'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categories' => ['privates', '.errored..service_locator.IzzSjso.App\\Entity\\Categories', NULL, 'Cannot autowire service ".service_locator.IzzSjso": it references class "App\\Entity\\Categories" but no such service exists.'],
        ], [
            'categories' => 'App\\Entity\\Categories',
        ]);
    }
}
