<?php

namespace ContainerJyFT97M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NnJ950IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nnJ950I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nnJ950I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clandar' => ['privates', '.errored..service_locator.nnJ950I.App\\Entity\\Clandar', NULL, 'Cannot autowire service ".service_locator.nnJ950I": it references class "App\\Entity\\Clandar" but no such service exists.'],
        ], [
            'clandar' => 'App\\Entity\\Clandar',
        ]);
    }
}
