<?php

namespace ContainerJyFT97M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClandarService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nnJ950I.App\Entity\Clandar' shared service.
     *
     * @return \App\Entity\Clandar
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.nnJ950I": it references class "App\\Entity\\Clandar" but no such service exists.');
    }
}
