<?php

namespace ContainerJyFT97M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategories2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IzzSjso.App\Entity\Categories' shared service.
     *
     * @return \App\Entity\Categories
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.IzzSjso": it references class "App\\Entity\\Categories" but no such service exists.');
    }
}
