<?php

namespace ContainerJyFT97M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVacanceFermetureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qyorV7d.App\Entity\VacanceFermeture' shared service.
     *
     * @return \App\Entity\VacanceFermeture
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qyorV7d": it references class "App\\Entity\\VacanceFermeture" but no such service exists.');
    }
}
